DROP TABLE IF EXISTS `USER_INFO`;
CREATE TABLE IF NOT EXISTS `USER_INFO` (
   `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
   `USER_FIRST_NAME` varchar(40) NOT NULL,
   `USER_LAST_NAME` varchar(40) NOT NULL,
   `IS_ADMIN` BOOLEAN NOT NULL DEFAULT FALSE,
   `EMAIL_ID` varchar(40) NOT NULL DEFAULT '',
   `PASSWORD` varchar(100) NOT NULL,
   `UPDATE_DTM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`USER_ID`)
);

DROP TABLE IF EXISTS `LEAGUE_INFO`;
CREATE TABLE IF NOT EXISTS `LEAGUE_INFO` (
   `LEAGUE_ID` int(11) NOT NULL AUTO_INCREMENT,
   `LEAGUE_NAME` varchar(40) NOT NULL,
   `ADMIN_ID` int(11) NOT NULL,
   `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
   `UPDATE_DTM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`LEAGUE_ID`)
);
ALTER TABLE LEAGUE_INFO AUTO_INCREMENT = 1000;

DROP TABLE IF EXISTS `TEAM_INFO`;
CREATE TABLE IF NOT EXISTS `TEAM_INFO` (
   `TEAM_ID` int(11) NOT NULL AUTO_INCREMENT,
   `TEAM_NAME` varchar(40) NOT NULL,
   `LEAGUE_ID` int(11) NOT NULL,
   `UPDATE_DTM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`TEAM_ID`)
);

DROP TABLE IF EXISTS `USER_TEAM_INFO`;
CREATE TABLE IF NOT EXISTS `USER_TEAM_INFO` (
   `TEAM_ID` int(11) NOT NULL,
   `USER_ID` int(11) NOT NULL,
   `START_DTM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `END_DTM` timestamp,
   `UPDATE_DTM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`TEAM_ID`,`USER_ID`)
);


DROP TABLE IF EXISTS `PLAYER_INFO`;
CREATE TABLE IF NOT EXISTS `PLAYER_INFO` (
  `PLAYER_ID` int(11) NOT NULL,
  `FIRST_NAME` varchar(40) NOT NULL,
  `LAST_NAME` varchar(40) NOT NULL,
  `BAT_BOWL_STYLE` varchar(100) NOT NULL,
  `CATEGORY` varchar(100) NOT NULL,
  `BASE_PRICE` int(11) NOT NULL,
  `RUNSFACTOR` int(11) NOT NULL DEFAULT '1',
  `IPL_TEAM_ID` int(11) NOT NULL,
  `UPDATE_DTM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PLAYER_ID`)
);
DROP TABLE IF EXISTS `AUCTION_MESSAGES_INFO`;
CREATE TABLE IF NOT EXISTS `AUCTION_MESSAGES_INFO` (
   `MESSAGE_ID` int(11) NOT NULL AUTO_INCREMENT,
   `USER_NAME` varchar(40) NOT NULL,
   `USER_ID` int(11) NOT NULL DEFAULT 0,
   `MESSAGE` varchar(40) NOT NULL,
   `UPDATE_DTM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`MESSAGE_ID`)
);

DROP TABLE IF EXISTS `AUCTION_PLAYER_INFO`;
CREATE TABLE IF NOT EXISTS `AUCTION_PLAYER_INFO` (
   `AUCTION_ID` int(11) DEFAULT 1,
   `PLAYER_NAME` varchar(40) NOT NULL,
   `PRICE` FLOAT NOT NULL DEFAULT 0,
   `UPDATE_DTM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`AUCTION_ID`)
);